"""Fixture gate for PEV site contracts (Task 4.1).

Every site adapter (Task 4.2+) is built against a fixed fixture captured by
``tests/manual/probe_pev_site.py``. These fixtures are the input contract: they
must declare a *provable* positive terminal signal (or a legitimate blocked
marker) and must never carry live credentials, cookies, or PII.

The fixtures are generated by the probe, never hand-edited.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

FIXTURE_ROOT = Path(__file__).resolve().parents[2] / "fixtures" / "job_discovery"
SITES = ("moka", "feishu", "inovance", "xiaohongshu")

# Structured terminal signals the probe may populate. A site needs at least one
# of these (Task 4.1 Step 2), OR a non-empty blocked_markers list (Step 4 allows
# a valid blocked fixture instead of bypassing an auth wall).
POSITIVE_TERMINAL_KEYS = (
    "total_count_path",
    "has_more_path",
    "next_cursor_path",
    "terminal_selector",
    "single_page_proof",
)

# Forbidden substrings in any fixture file (Task 4.1 sanitization rule).
SECRET_SUBSTRINGS = ("authorization", "cookie", "bearer ")


def load_fixture(site: str) -> dict:
    """Return the parsed contract.json for a site, or {} if absent/unreadable."""
    contract = FIXTURE_ROOT / site / "contract.json"
    if not contract.exists():
        return {}
    try:
        return json.loads(contract.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def all_fixture_text() -> str:
    """Concatenate every byte written under the four site fixture dirs."""
    parts: list[str] = []
    for site in SITES:
        site_dir = FIXTURE_ROOT / site
        if not site_dir.exists():
            continue
        for path in sorted(site_dir.rglob("*")):
            if path.is_file():
                parts.append(path.read_text(encoding="utf-8", errors="ignore"))
    return "\n".join(parts)


@pytest.mark.parametrize("site", SITES)
def test_fixture_declares_positive_terminal_signal(site: str) -> None:
    fixture = load_fixture(site)
    assert fixture, (
        f"fixture missing for site={site}; run: "
        f"python tests/manual/probe_pev_site.py --site {site} --url <url> "
        f"--output tests/fixtures/job_discovery/{site}"
    )
    has_positive = any(fixture.get(key) for key in POSITIVE_TERMINAL_KEYS)
    has_blocked = bool(fixture.get("blocked_markers"))
    assert has_positive or has_blocked, (
        f"site={site} fixture declares no positive terminal signal "
        f"(one of {POSITIVE_TERMINAL_KEYS}) and no blocked marker"
    )


def test_fixture_never_contains_secret_headers() -> None:
    text = all_fixture_text().lower()
    for secret in SECRET_SUBSTRINGS:
        assert secret not in text, (
            f"fixture text contains forbidden substring {secret!r}; "
            f"probe must strip credentials/cookies before writing"
        )


def test_moka_fixture_carries_job_hash_route_contract() -> None:
    """The moka contract is the input spec for ``MokaCrawlDriver.from_fixture``.

    Task 4.2's driver reads ``page_url``, ``expected_listing_count``,
    ``single_page_proof`` and ``sample_listings`` (each a ``#/job/`` hash route)
    from this contract; the gate test pins those fields so the driver has a
    stable, fixture-proven input.
    """
    fixture = load_fixture("moka")
    assert fixture.get("data_source") == "dom_rendered"
    assert fixture.get("obfuscated_xhr") is True
    assert fixture.get("single_page_proof") == "single_page_mokahr_hash_jobs"
    expected = fixture.get("expected_listing_count")
    assert isinstance(expected, int) and expected > 0
    samples = fixture.get("sample_listings") or []
    assert len(samples) == expected, (
        "moka sample_listings count must match expected_listing_count for "
        "deterministic unit replay"
    )
    for sample in samples:
        detail_url = sample.get("detail_url", "")
        assert "#/job/" in detail_url, (
            f"moka sample detail_url is not a job-level hash route: {detail_url}"
        )
        assert sample.get("title"), "moka sample listing must carry a title"


def test_feishu_fixture_carries_position_detail_contract() -> None:
    """The feishu contract is the input spec for ``FeishuCrawlDriver.from_fixture``.

    Task 4.3's driver reads ``page_url``, the page-number ``items_path`` /
    ``total_count_path``, ``expected_listing_count`` and ``sample_listings`` from
    this contract. Sample ``id`` fields are PII-redacted, so the job-level
    ``/campus/position/{position_id}/detail`` routes are sourced from the
    fixture's public ``detail_url_examples`` (real numeric position ids); the
    gate pins that pairing so the driver has a stable, fixture-proven input.
    """
    import re

    fixture = load_fixture("feishu")
    assert fixture.get("data_source") == "json_xhr"
    assert fixture.get("items_path") == "$.data.job_post_list"
    assert fixture.get("total_count_path") == "$.data.count"
    expected = fixture.get("expected_listing_count")
    assert isinstance(expected, int) and expected > 0
    samples = fixture.get("sample_listings") or []
    assert len(samples) == expected, (
        "feishu sample_listings count must match expected_listing_count for "
        "deterministic unit replay"
    )
    detail_urls = fixture.get("detail_url_examples") or []
    assert len(detail_urls) >= len(samples), (
        "feishu detail_url_examples must cover every sample (sample ids are "
        "PII-redacted; real position ids come from detail_url_examples)"
    )
    for detail_url in detail_urls[: len(samples)]:
        assert re.search(r"/campus/position/\d+/detail", detail_url), (
            f"feishu detail_url_example is not a position detail route: {detail_url}"
        )
    for sample in samples:
        assert sample.get("title"), "feishu sample listing must carry a title"


def test_inovance_fixture_carries_jobs_hash_route_contract() -> None:
    """The inovance contract is the input spec for ``InovanceCrawlDriver.from_fixture``.

    Task 4.4's driver reads ``page_url``, ``single_page_proof`` and
    ``sample_listings`` (each a ``#/jobs/<uuid>`` hash route) from this
    contract; the gate test pins those fields so the driver has a stable,
    fixture-proven input. The ``#/jobs`` fragment is shared by the listing
    page and every detail route, which is why the driver leaves ``apply_url``
    as ``None`` rather than falling back to the listing page.
    """
    fixture = load_fixture("inovance")
    assert fixture.get("data_source") == "dom_rendered"
    assert fixture.get("single_page_proof") == "single_page_inovance_hash_jobs"
    expected = fixture.get("expected_listing_count")
    assert isinstance(expected, int) and expected > 0
    samples = fixture.get("sample_listings") or []
    assert len(samples) == expected, (
        "inovance sample_listings count must match expected_listing_count for "
        "deterministic unit replay"
    )
    for sample in samples:
        detail_url = sample.get("detail_url", "")
        assert "#/jobs/" in detail_url, (
            f"inovance sample detail_url is not a job-level hash route: {detail_url}"
        )
        assert sample.get("title"), "inovance sample listing must carry a title"


def test_xiaohongshu_fixture_carries_api_cursor_contract() -> None:
    """The xiaohongshu contract is the input spec for ``XiaohongshuCrawlDriver.from_fixture``.

    Task 5's driver reads ``page_url``, the API-cursor ``items_path`` /
    ``total_count_path``, ``expected_listing_count`` and ``sample_listings``
    (each carrying a real ``positionId`` with ``duty`` + ``qualification`` JD
    body) from this contract. The probe captured a DOM terminal selector
    (``ant_pagination_disabled``) rather than a JSON cursor path, so the
    replay simulates cursor progression and terminates on ``next_cursor_null``.
    """
    fixture = load_fixture("xiaohongshu")
    assert fixture.get("data_source") == "json_xhr"
    assert fixture.get("items_path") == "$.data.list"
    assert fixture.get("total_count_path") == "$.data.total"
    total = fixture.get("total_count_value")
    assert isinstance(total, int) and total > 0, (
        "xiaohongshu fixture must declare the public $.data.total count"
    )
    expected = fixture.get("expected_listing_count")
    assert isinstance(expected, int) and expected > 0
    samples = fixture.get("sample_listings") or []
    assert len(samples) == expected, (
        "xiaohongshu sample_listings count must match expected_listing_count "
        "for deterministic unit replay"
    )
    for sample in samples:
        assert sample.get("positionId"), (
            "xiaohongshu sample must carry a real positionId (the detail route key)"
        )
        assert sample.get("positionName"), "xiaohongshu sample must carry a title"
        # Each listing's JD body comes from duty + qualification, never a blob split.
        assert sample.get("duty") or sample.get("qualification"), (
            "xiaohongshu sample must carry JD body fields (duty/qualification)"
        )
